// Plugin-provided configuration.
//
// `worker-configuration.d.ts` is regenerated by `wrangler types`. Wrangler
// declares bindings and plain-text vars from `wrangler.jsonc`, but deliberately
// cannot discover deployed secrets or optional feature flags. Declare those
// here and let interface merging fold them into the global `Env`.
//
// Keep this file free of imports/exports: that is what makes it an ambient
// global augmentation. Adding either turns it into a module and the `Env`
// merge silently stops working.
interface Env {
  /** Telegram credentials are deployed as Worker secrets. */
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;

  /** Brave Search API subscription token. Presence enables the websearch plugin. */
  BRAVE_API_KEY?: string;
  /** Explicit on/off override for the websearch plugin (e.g. "true"/"false"). */
  ENABLE_WEBSEARCH?: string;
  /** Explicit on/off override for the reminders plugin (e.g. "true"/"false"). */
  ENABLE_REMINDERS?: string;

  /** Explicit on/off override for the weather plugin (e.g. "true"/"false"). */
  ENABLE_WEATHER?: string;

  /** Explicit on/off override for the tic-tac-toe plugin (e.g. "true"/"false"). */
  ENABLE_TICTACTOE?: string;

  /** GitHub token (contents + PR write) for the selfdev plugin. */
  GITHUB_TOKEN?: string;
  /** Explicit on/off override for the selfdev plugin (e.g. "true"/"false"). */
  ENABLE_SELFDEV?: string;

  /**
   * Sandbox container binding (Cloudflare Sandbox SDK), used by selfdev to
   * verify proposed changes (clone + pnpm typecheck) before opening a PR.
   * Inline import keeps this file an ambient global augmentation.
   */
  Sandbox: DurableObjectNamespace<import("@cloudflare/sandbox").Sandbox>;

  /**
   * Service binding (RPC) to the tellboy-deployer control-plane Worker. The
   * bot can deploy itself and read its own telemetry through this, without
   * ever holding the underlying Cloudflare/GitHub credentials. Structural type
   * mirrors the deployer's WorkerEntrypoint methods (see deployer/src/index.ts).
   */
  DEPLOYER: Service & {
    deploy(): Promise<{ ok: boolean; status?: string; error?: string }>;
    readLogs(opts?: {
      minutesAgo?: number;
      limit?: number;
      level?: string;
    }): Promise<
      | {
          events: Array<{
            timestamp?: number;
            level?: string;
            message?: string;
            outcome?: string;
          }>;
        }
      | { error: string }
    >;
  };
  /** Explicit on/off override for the deploy + logs (selfops) plugins. */
  ENABLE_DEPLOY?: string;
  ENABLE_LOGS?: string;

  /**
   * Kill switch for Bot API 10.1 Rich Messages (sendRichMessage). Rich delivery
   * is ON by default; set this to a falsy value ("false"/"0"/"off") to force the
   * legacy HTML/MarkdownV2 path. Rich sends fall back automatically on failure,
   * so this only chooses which format is attempted first.
   */
  ENABLE_RICH_MESSAGES?: string;

  /**
   * Kill switch for inbound voice-note transcription. Transcription runs on the
   * existing AI binding (no new credential) and is ON by default; set this to a
   * falsy value ("false"/"0"/"off") to leave voice/audio notes untranscribed.
   */
  ENABLE_VOICE?: string;

  /**
   * MCP integrations gateway config: a JSON array of `{ name, url, apiKey? }`
   * naming external MCP servers to connect, whose tools auto-merge into the
   * model's toolset (see src/plugins/mcp.ts). Presence of a non-empty, valid
   * array enables the mcp plugin; absence (the default) leaves it off. This is
   * plain integration config, not a powerful platform credential — any per-server
   * `apiKey` only authenticates to that third-party MCP endpoint.
   */
  MCP_SERVERS?: string;
  /** Explicit on/off override for the mcp plugin (e.g. "true"/"false"). */
  ENABLE_MCP?: string;
}
