// Plugin-provided configuration.
//
// `worker-configuration.d.ts` is regenerated by `wrangler types` and only
// includes secrets/flags that happen to be present in `.dev.vars` at
// generation time. These plugin vars are optional, so we declare them here as
// optional and let interface merging fold them into the global `Env`.
//
// Keep this file free of imports/exports: that is what makes it an ambient
// global augmentation. Adding either turns it into a module and the `Env`
// merge silently stops working.
interface Env {
  /** Brave Search API subscription token. Presence enables the websearch plugin. */
  BRAVE_API_KEY?: string;
  /** Explicit on/off override for the websearch plugin (e.g. "true"/"false"). */
  ENABLE_WEBSEARCH?: string;
  /** Explicit on/off override for the reminders plugin (e.g. "true"/"false"). */
  ENABLE_REMINDERS?: string;
}
