// Plugin-provided configuration.
//
// `worker-configuration.d.ts` is regenerated by `wrangler types` and only
// includes secrets/flags that happen to be present in `.dev.vars` at
// generation time. These plugin vars are optional, so we declare them here as
// optional and let interface merging fold them into the global `Env`.
//
// Keep this file free of imports/exports: that is what makes it an ambient
// global augmentation. Adding either turns it into a module and the `Env`
// merge silently stops working.
interface Env {
  /** Brave Search API subscription token. Presence enables the websearch plugin. */
  BRAVE_API_KEY?: string;
  /** Explicit on/off override for the websearch plugin (e.g. "true"/"false"). */
  ENABLE_WEBSEARCH?: string;
  /** Explicit on/off override for the reminders plugin (e.g. "true"/"false"). */
  ENABLE_REMINDERS?: string;

  /** GitHub token (contents + PR write) for the selfdev plugin. */
  GITHUB_TOKEN?: string;
  /** Target repo for selfdev, as "owner/name", e.g. "MattieTK/tellboy". */
  GITHUB_REPO?: string;
  /** Explicit on/off override for the selfdev plugin (e.g. "true"/"false"). */
  ENABLE_SELFDEV?: string;

  /**
   * Sandbox container binding (Cloudflare Sandbox SDK), used by selfdev to
   * verify proposed changes (clone + pnpm typecheck) before opening a PR.
   * Inline import keeps this file an ambient global augmentation.
   */
  Sandbox: DurableObjectNamespace<import("@cloudflare/sandbox").Sandbox>;

  /**
   * Service binding (RPC) to the tellboy-deployer control-plane Worker. The
   * bot can deploy itself and read its own telemetry through this, without
   * ever holding the underlying Cloudflare/GitHub credentials. Structural type
   * mirrors the deployer's WorkerEntrypoint methods (see deployer/src/index.ts).
   */
  DEPLOYER?: {
    deploy(): Promise<{ ok: boolean; status?: string; error?: string }>;
    readLogs(opts?: {
      minutesAgo?: number;
      limit?: number;
      level?: string;
    }): Promise<
      | {
          events: Array<{
            timestamp?: number;
            level?: string;
            message?: string;
            outcome?: string;
          }>;
        }
      | { error: string }
    >;
  };
  /** Explicit on/off override for the deploy + logs (selfops) plugins. */
  ENABLE_DEPLOY?: string;
  ENABLE_LOGS?: string;
}
